const keys = [
  [
    {
      key: '`',
      shiftKey: '~',
      code: 'Backquote',
      isWritable: true,
    },
    {
      key: '1',
      shiftKey: '!',
      code: 'Digit1',
      isWritable: true,
    },
    {
      key: '2',
      shiftKey: '@',
      code: 'Digit2',
      isWritable: true,
    },
    {
      key: '3',
      shiftKey: '#',
      code: 'Digit3',
      isWritable: true,
    },
    {
      key: '4',
      shiftKey: '$',
      code: 'Digit4',
      isWritable: true,
    },
    {
      key: '5',
      shiftKey: '%',
      code: 'Digit5',
      isWritable: true,
    },
    {
      key: '6',
      shiftKey: '^',
      code: 'Digit6',
      isWritable: true,
    },
    {
      key: '7',
      shiftKey: '&',
      code: 'Digit7',
      isWritable: true,
    },
    {
      key: '8',
      shiftKey: '*',
      code: 'Digit8',
      isWritable: true,
    },
    {
      key: '9',
      shiftKey: '(',
      code: 'Digit9',
      isWritable: true,
    },
    {
      key: '0',
      shiftKey: ')',
      code: 'Digit0',
      isWritable: true,
    },
    {
      key: '-',
      shiftKey: '_',
      code: 'Minus',
      isWritable: true,
    },
    {
      key: '=',
      shiftKey: '+',
      code: 'Equal',
      isWritable: true,
    },
    {
      key: 'Backspace',
      shiftKey: 'Backspace',
      code: 'Backspace',
      isWritable: false,
    },
  ],
  [
    {
      key: 'Tab',
      shiftKey: 'Tab',
      code: 'Tab',
      isWritable: false,
    },
    {
      key: 'q',
      shiftKey: 'Q',
      code: 'KeyQ',
      isWritable: true,
    },
    {
      key: 'w',
      shiftKey: 'W',
      code: 'KeyW',
      isWritable: true,
    },
    {
      key: 'e',
      shiftKey: 'E',
      code: 'KeyE',
      isWritable: true,
    },
    {
      key: 'r',
      shiftKey: 'R',
      code: 'KeyR',
      isWritable: true,
    },
    {
      key: 't',
      shiftKey: 'T',
      code: 'KeyT',
      isWritable: true,
    },
    {
      key: 'y',
      shiftKey: 'Y',
      code: 'KeyY',
      isWritable: true,
    },
    {
      key: 'u',
      shiftKey: 'U',
      code: 'KeyU',
      isWritable: true,
    },
    {
      key: 'i',
      shiftKey: 'I',
      code: 'KeyI',
      isWritable: true,
    },
    {
      key: 'o',
      shiftKey: 'O',
      code: 'KeyO',
      isWritable: true,
    },
    {
      key: 'p',
      shiftKey: 'P',
      code: 'KeyP',
      isWritable: true,
    },
    {
      key: '[',
      shiftKey: '{',
      code: 'BracketLeft',
      isWritable: true,
    },
    {
      key: ']',
      shiftKey: '}',
      code: 'BracketRight',
      isWritable: true,
    },
    {
      key: '\\',
      shiftKey: '|',
      code: 'Backslash',
      isWritable: true,
    },
    {
      key: 'Delete',
      shiftKey: 'Delete',
      code: 'Delete',
      isWritable: false,
    },
  ],
  [
    {
      key: 'CapsLock',
      shiftKey: 'CapsLk',
      code: 'CapsLock',
      isWritable: false,
    },
    {
      key: 'a',
      shiftKey: 'A',
      code: 'KeyA',
      isWritable: true,
    },
    {
      key: 's',
      shiftKey: 'S',
      code: 'KeyS',
      isWritable: true,
    },
    {
      key: 'd',
      shiftKey: 'D',
      code: 'KeyD',
      isWritable: true,
    },
    {
      key: 'f',
      shiftKey: 'F',
      code: 'KeyF',
      isWritable: true,
    },
    {
      key: 'g',
      shiftKey: 'G',
      code: 'KeyG',
      isWritable: true,
    },
    {
      key: 'h',
      shiftKey: 'H',
      code: 'KeyH',
      isWritable: true,
    },
    {
      key: 'j',
      shiftKey: 'J',
      code: 'KeyJ',
      isWritable: true,
    },
    {
      key: 'k',
      shiftKey: 'K',
      code: 'KeyK',
      isWritable: true,
    },
    {
      key: 'l',
      shiftKey: 'L',
      code: 'KeyL',
      isWritable: true,
    },
    {
      key: ':',
      shiftKey: ';',
      code: 'Semicolon',
      isWritable: true,
    },
    {
      key: "'",
      shiftKey: '"',
      code: 'Quote',
      isWritable: true,
    },
    {
      key: 'Enter',
      shiftKey: 'Enter',
      code: 'Enter',
      isWritable: true,
    },
  ],
  [
    {
      key: 'Shift',
      shiftKey: 'Shift',
      code: 'ShiftLeft',
      isWritable: false,
    },
    {
      key: 'z',
      shiftKey: 'Z',
      code: 'KeyZ',
      isWritable: true,
    },
    {
      key: 'x',
      shiftKey: 'X',
      code: 'KeyX',
      isWritable: true,
    },
    {
      key: 'c',
      shiftKey: 'C',
      code: 'KeyC',
      isWritable: true,
    },
    {
      key: 'v',
      shiftKey: 'V',
      code: 'KeyV',
      isWritable: true,
    },
    {
      key: 'b',
      shiftKey: 'B',
      code: 'KeyB',
      isWritable: true,
    },
    {
      key: 'n',
      shiftKey: 'N',
      code: 'KeyN',
      isWritable: true,
    },
    {
      key: 'm',
      shiftKey: 'M',
      code: 'KeyM',
      isWritable: true,
    },
    {
      key: ',',
      shiftKey: '<',
      code: 'Comma',
      isWritable: true,
    },
    {
      key: '.',
      shiftKey: '>',
      code: 'Period',
      isWritable: true,
    },
    {
      key: '/',
      shiftKey: '?',
      code: 'Slash',
      isWritable: true,
    },
    {
      key: '↑',
      shiftKey: '↑',
      code: 'ArrowUp',
      isWritable: true,
    },
    {
      key: 'Shift',
      shiftKey: 'Shift',
      code: 'ShiftRight',
      isWritable: false,
    },
  ],
  [
    {
      key: 'Ctrl',
      shiftKey: 'Ctrl',
      code: 'ControlLeft',
      isWritable: false,
    },
    {
      key: 'Win',
      shiftKey: 'Win',
      code: 'MetaLeft',
      isWritable: false,
    },
    {
      key: 'Alt',
      shiftKey: 'Alt',
      code: 'AltLeft',
      isWritable: false,
    },
    {
      key: ' ',
      shiftKey: ' ',
      code: 'Space',
      isWritable: true,
    },
    {
      key: '←',
      shiftKey: '←',
      code: 'ArrowLeft',
      isWritable: true,
    },
    {
      key: '↓',
      shiftKey: '↓',
      code: 'ArrowDown',
      isWritable: true,
    },
    {
      key: '→',
      shiftKey: '→',
      code: 'ArrowRight',
      isWritable: true,
    },
    {
      key: 'Alt',
      shiftKey: 'Alt',
      code: 'AltRight',
      isWritable: false,
    },
    {
      key: 'Ctrl',
      shiftKey: 'Ctrl',
      code: 'ControlRight',
      isWritable: false,
    },
  ],
];

export default keys;
